### ISSUE TITLE
FRQ - Explicit support for multiple routes

### ISSUE THREAD

**Issue by pmackinney** [NothNoth/MIDIRouter#3]
Feature Request or maybe just a support request

I want to route both my MPK mini and my SQ-1 to my Neutron, the config file doesn't seem to support this so I'm running multiple instances of midirouter. This seems to work. Is it the best approach?

`cat .midirouter.json.mini .midirouter.json.sq1`
`{`
`    "SourceDevice": "MPK mini",`
`    "DestinationDevice": "Neutron(1)",`
`    "DefaultPassthrough": true,`
`    "Verbose": true`
`}`
`{`
`    "SourceDevice": "SEQ IN",`
`    "DestinationDevice": "Neutron(1)",`
`    "DefaultPassthrough": true,`
`    "Verbose": true`
`}`

**Comment by NothNoth** [comment]
Hi,
Yes I think it's the best way to do it
